POST http://localhost:4000/app/signup
Content-Type: application/json


{
    "fullName" : "Dhananjaysoni",
    "email" : "dhananjaysoni2920@gmail.com",
    "mobileNumber" : "192039485933",
    "password" : "joseyjosey"
}